from typing import Protocol


class IPostLikeDm(Protocol):
    async def lock_post(self, *, post_id: int) -> bool: ...

    async def exists(self, *, user_id: int, post_id: int) -> bool: ...

    async def create(self, *, user_id: int, post_id: int) -> None: ...

    async def delete(self, *, user_id: int, post_id: int) -> None: ...


class ICommentLikeDm(Protocol):
    async def lock_comment(self, *, comment_id: int) -> bool: ...

    async def exists(self, *, user_id: int, comment_id: int) -> bool: ...

    async def create(self, *, user_id: int, comment_id: int) -> None: ...

    async def delete(self, *, user_id: int, comment_id: int) -> None: ...
